version: '3.7'
services:
  db:
    build: 
      context: .
      dockerfile: ./SQL/dockerfile
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - web_data:/app
    
volumes:
  db_data:
  web_data: