FROM mysql:latest

# Establecer las variables de entorno para la configuración de MySQL
ENV MYSQL_ROOT_PASSWORD=D34THN0T3
ENV MYSQL_DATABASE=usuarios

COPY ./SQL/registrados.sql /docker-entrypoint-initdb.d/